In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os

In [2]:
df_info = pd.read_pickle('../../../../../data/SPL/df_segments_updated.pkl')
# df_psd = pd.read_pickle('../../../../../data/SPL/psd_aplose_fq_filtered.pkl')
df_psd = pd.read_pickle('../../../../../data/SPL/psd_aplose_fq_filtered_no_background.pkl') # without background noise
output_path = "/home/imonge/Documents/annotations"
# Delete columns 'signal' and 'sampling_rate'
df_info = df_info.drop(columns=['signal', 'sampling_rate'], errors='ignore')

In [3]:
# Reset indexes for both datasets before merging
df_info = df_info.reset_index(drop=True)
df_psd = df_psd.reset_index(drop=True)

# Merge both dataframes line by line
df_merged = pd.concat([df_info, df_psd], axis=1)

# Post-merge checking
assert df_merged.shape[0] == df_info.shape[0] == df_psd.shape[0], "Allignment error after merging"

labels = df_merged['label'].unique()

AssertionError: Allignment error after merging

In [4]:
df_info

,start_datetime,end_datetime,station,label,start_frequency,end_frequency,type,filename,confidence,SPL_db,SEL_db,zero_to_pk_db,duration,mean_start_frequency,mean_end_frequency,species
0,2021-08-15 16:07:26.061000+00:00,2021-08-15 16:07:28.072000+00:00,MAHY11,ind_8s,59.0,91.0,BOX,00838_MAHY1_20210815_160618.wav,Sure,111.967541,114.977841,120.888283,2.011,60.865908,85.457306,ind
1,2021-08-15 16:07:34.551000+00:00,2021-08-15 16:07:36.711000+00:00,MAHY11,ind_8s,56.0,85.0,BOX,00838_MAHY1_20210815_160618.wav,Sure,118.328748,121.653132,131.593559,2.16,60.865908,85.457306,ind
2,2021-08-15 16:07:43.339000+00:00,2021-08-15 16:07:45.797000+00:00,MAHY11,ind_8s,61.0,107.0,BOX,00838_MAHY1_20210815_160618.wav,Sure,111.936062,115.820330,121.529399,2.458,60.865908,85.457306,ind
3,2021-08-15 16:07:51.308000+00:00,2021-08-15 16:07:54.063000+00:00,MAHY11,ind_8s,58.0,106.0,BOX,00838_MAHY1_20210815_160618.wav,Sure,108.274830,112.654976,116.596061,2.755,60.865908,85.457306,ind
4,2021-08-15 16:08:17.001000+00:00,2021-08-15 16:08:18.491000+00:00,MAHY11,ind_8s,57.0,105.0,BOX,00838_MAHY1_20210815_160618.wav,Sure,113.682778,115.382949,125.971264,1.49,60.865908,85.457306,ind
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5414,2024-09-04 22:56:06+00:00,2024-09-04 23:06:06+00:00,MAHY43,ship_noise,0.0,120.0,WEAK,01127_MAHY3_20240904_225606.wav,Sure,111.360309,139.141731,124.083464,None,0.000000,120.000000,NaN
5415,2024-09-11 04:31:20+00:00,2024-09-11 04:41:20+00:00,MAHY43,ship_noise,0.0,120.0,WEAK,01242_MAHY3_20240911_043120.wav,Sure,112.260670,140.042092,125.084105,None,0.000000,120.000000,NaN
5416,2024-09-11 09:20:50+00:00,2024-09-11 09:30:50+00:00,MAHY41,ship_noise,0.0,120.0,WEAK,01640_MAHY1_20240911_092050.wav,Sure,109.540405,137.321827,122.289855,None,0.000000,120.000000,NaN
5417,2024-09-15 09:01:38+00:00,2024-09-15 09:11:38+00:00,MAHY41,ship_noise,0.0,120.0,WEAK,01013_MAHY1_20240915_090138.wav,Sure,110.408427,138.189849,123.077013,None,0.000000,120.000000,NaN
5418,2024-09-19 13:26:22+00:00,2024-09-19 13:36:22+00:00,MAHY41,ship_noise,0.0,120.0,WEAK,01035_MAHY1_20240919_132622.wav,Sure,109.042894,136.824316,121.607548,None,0.000000,120.000000,NaN

In [5]:
df_psd

,0.00000,0.46875,0.93750,1.40625,1.87500,2.34375,2.81250,3.28125,3.75000,4.21875,...,115.78125,116.25000,116.71875,117.18750,117.65625,118.12500,118.59375,119.06250,119.53125,120.00000
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5352,NaN,0.000000e+00,0.000000e+00,0.000000e+00,8.644005e+08,2.828048e+08,3.555315e+08,1.984465e+08,4.706341e+07,1.901098e+08,...,0.000000e+00,0.000000e+00,0.000000e+00,4.970763e+04,0.000000e+00,4.933688e+04,5.914910e+05,2.658000e+05,6.130390e+04,NaN
5353,NaN,7.392448e+06,9.047780e+08,4.559259e+08,0.000000e+00,0.000000e+00,3.294150e+08,3.083164e+06,2.638736e+08,1.060663e+08,...,0.000000e+00,8.391707e+05,1.194920e+06,1.460146e+06,1.260112e+06,2.307192e+05,0.000000e+00,0.000000e+00,0.000000e+00,NaN
5354,NaN,0.000000e+00,7.728783e+08,3.696178e+09,3.742528e+09,2.465659e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,2.003660e+06,0.000000e+00,0.000000e+00,7.784264e+05,2.422055e+06,1.837519e+06,7.748328e+05,0.000000e+00,0.000000e+00,NaN
5355,NaN,0.000000e+00,0.000000e+00,2.326113e+09,2.869215e+08,1.554058e+09,1.156321e+09,6.265439e+08,3.082816e+08,2.813430e+08,...,5.657903e+05,3.993368e+05,5.040729e+04,4.508547e+05,3.893495e+05,3.503357e+04,0.000000e+00,4.448443e+04,1.301163e+04,NaN
5356,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.937213e+08,1.605440e+08,1.459633e+08,1.251037e+08,5.866445e+07,2.016190e+07,1.011460e+08,5.444597e+07,4.455173e+06,NaN

In [ ]:
# Plot labels individually with mean PSD on the 4-year data
for label in labels:
    df_label = df_merged[df_merged['label'] == label]

    # Only take species (no geophony or anthropophony)
    if df_label['species'].replace('', np.nan).notna().sum() == 0:
        continue

    # Extract only frequency columns
    df_label_psd = df_label[df_psd.columns]

    # Mean PSD by label ###
    mean_psd = df_label_psd.mean(axis=0)

    # Convert to dB re 1 µPa²/Hz
    mean_psd[mean_psd < 1e-12] = np.nan # avoid log(0), put Nan instead
    mean_psd_db = 10 * np.log10(mean_psd)

    plt.figure(figsize=(12,6))
    plt.plot(mean_psd_db.index, mean_psd_db.values, label=label, color='darkcyan')
    plt.xlabel('Frequency (Hz)')
    plt.ylabel('Mean amplitude (dB re 1 µPa²/Hz)') ## Chechk if it is in fact 1µPa²
    plt.title(f'Peak frequencies in the annotation box - {label}')
    plt.style.use('default')
    plt.grid(True, alpha=0.4, linestyle='--')
    plt.tight_layout()
    plt.show()

    # plt.savefig(os.path.join(output_path, 'peak_fq_no_background', f'peak_frequency_no_background_{label}.png'))
    # plt.close()

In [ ]:
# # Plot labels individually by year
# # Extract year from start datetime
# df_merged['start_datetime'] = pd.to_datetime(df_merged['start_datetime'], errors='coerce')
# df_merged['year'] = df_merged['start_datetime'].dt.year.astype(str)
# 
# 
# # Plot for each label and each year
# for label in labels:
#     df_label = df_merged[df_merged['label'] == label]
# 
#     # Only take species (no geophony or anthropophony)
#     if df_label['species'].replace('', np.nan).notna().sum() == 0:
#         continue
# 
#     for year in sorted(df_label['year'].unique()):
#         df_label_year = df_label[df_label['year'] == year]
# 
#         if df_label_year.empty:
#             continue
# 
#         # Extract only frequency columns
#         df_label_psd = df_label_year[df_psd.columns]
# 
#         # Mean PSD by label
#         mean_psd = df_label_psd.mean(axis=0)
# 
#         # Convert to dB re 1 µPa²/Hz
#         mean_psd[mean_psd < 1e-12] = np.nan # avoid log(0), put Nan instead
#         mean_psd_db = 10 * np.log10(mean_psd)
# 
#         plt.figure(figsize=(12,6))
#         plt.plot(mean_psd_db.index, mean_psd_db.values, label=label, color='darkcyan')
#         plt.xlabel('Frequency (Hz)')
#         plt.ylabel('Mean amplitude (dB re 1 µPa²/Hz)')
#         plt.title(f'Mean spectra - {label} ({year})')
#         plt.style.use('default')
#         plt.grid(True, alpha=0.4, linestyle='--')
#         plt.tight_layout()
#         plt.show()
# 
#         # plt.savefig(os.path.join(output_path, 'peak_fq_yearly_no_background',f'{label}', f'peak_frequency_{label}_{year}_no_background.png'))
#         # plt.close()

In [ ]:
# Plot all labels
cmap = plt.get_cmap('tab20')
colors = {label: cmap(i % cmap.N) for i, label in enumerate(labels)}


plt.style.use('default')
fig, ax = plt.subplots(figsize=(14,8))

for label in labels:
    df_label = df_merged[df_merged['label'] == label]

    # Only take species (no geophony or anthropophony)
    if df_label['species'].replace('', np.nan).notna().sum() == 0:
        continue

    # Extract only frequency columns
    df_label_psd = df_label[df_psd.columns]

    # Mean PSD by label
    mean_psd = df_label_psd.mean(axis=0)

    # Convert to dB re 1 µPa²/Hz
    mean_psd[mean_psd < 1e-12] = np.nan # avoid log(0), put Nan instead
    mean_psd_db = 10 * np.log10(mean_psd)

    ax.plot(mean_psd_db.index, mean_psd_db.values, label=label, color=colors[label])

ax.set_xlabel('Frequency (Hz)')
ax.set_ylabel('Mean amplitude (dB re 1 µPa²/Hz)')
ax.set_xlim(13, 120)
ax.set_ylim(55, 102)
ax.set_title('Mean spectra')
ax.legend()
plt.grid(True, alpha=0.4, linestyle='--')
plt.tight_layout()
# plt.show()

plt.savefig(os.path.join(output_path, f'peak_frequency_all_no_background.png'))
plt.close()

In [ ]:
df_merged

In [ ]:
df_info

In [ ]:
df_psd